float:
  any:
  - base_args: ['@metric']
    constructor: Redisearch
    disabled: false
    docker_tag: ann-benchmarks-redisearch
    module: ann_benchmarks.algorithms.redisearch
    name: redisearch
    run_groups:
      redisearch:
        arg_groups: [[4]]
        args: {}
        query_args: [[10]]
