float:
  any:
  - base_args: ['@metric', '@dimension']
    constructor: Milvus
    disabled: false
    docker_tag: ann-benchmarks-milvus
    module: ann_benchmarks.algorithms.milvus
    name: Milvus(Knowhere)
    run_groups:
      HNSW:
        args:
          M: [96]
          efConstruction: 500
        query_args: [[800]]
